# Swarm policy: star-ring small swarms + 20% mesh explorer targeting unused areas
swarm_types:
  star_ring:
    size: small
    nodes: 5
    topology: star-ring
    role: primary
  mesh_explorer:
    size: micro
    nodes: 2
    topology: mesh
    role: explorer

routing:
  # 80% of tasks go to star-ring primary, 20% to mesh explorer
  allocation:
    star_ring: 0.8
    mesh_explorer: 0.2

exploration_bias:
  # Prefer cells/partitions with least recent usage
  strategy: least_recent
  decay_half_life_tasks: 200

partitions:
  # Logical space indexed by id; can be physical sectors or data shards
  count: 32
