# Default repository labels
- name: bug
  color: d73a4a
  description: Something isn’t working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: chore
  color: cccccc
  description: Build, tooling, or maintenance
- name: ci
  color: bfd4f2
  description: Continuous Integration changes
- name: dependencies
  color: 0366d6
  description: Dependency updates
