name: Labels Sync

on:
  workflow_dispatch:
  push:
    paths:
      - .github/labels.yml
      - .github/labels.yaml

permissions:
  contents: read
  issues: write

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Apply repository labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          yaml-file: .github/labels.yml
