name: Large File Guard
on: [pull_request, push]
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - shell: bash
        run: |
          MAX=52428800
          fail=0
          while IFS= read -r -d '' f; do
            size=$(stat -c%s "$f")
            if [ "$size" -gt "$MAX" ]; then
              echo "::error file=$f::File exceeds 50MB ($size bytes)"
              fail=1
            fi
          done < <(git ls-files -z)
          exit $fail
